# Generated by Django 2.2.1 on 2019-05-15 16:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Component Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ComponentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('h1', models.CharField(blank=True, help_text='If you want the main heading on the page to say something other than the above title field, enter it here.', max_length=100)),
                ('overview', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Rich Text')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], help_text='For displaying code to the reader of a page.', icon='code')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='HTML that will be rendered on the page. Use as a temporary solution or last resort for something fancy that has not been enabled in a proper Wagtail block yet.', icon='placeholder', label='Raw HTML'))], blank=True)),
                ('usage', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Rich Text')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], help_text='For displaying code to the reader of a page.', icon='code')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='HTML that will be rendered on the page. Use as a temporary solution or last resort for something fancy that has not been enabled in a proper Wagtail block yet.', icon='placeholder', label='Raw HTML'))], blank=True)),
                ('design', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Rich Text')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], help_text='For displaying code to the reader of a page.', icon='code')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='HTML that will be rendered on the page. Use as a temporary solution or last resort for something fancy that has not been enabled in a proper Wagtail block yet.', icon='placeholder', label='Raw HTML'))], blank=True)),
                ('code', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Rich Text')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], help_text='For displaying code to the reader of a page.', icon='code')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='HTML that will be rendered on the page. Use as a temporary solution or last resort for something fancy that has not been enabled in a proper Wagtail block yet.', icon='placeholder', label='Raw HTML'))], blank=True)),
                ('accessibility', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Rich Text')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], help_text='For displaying code to the reader of a page.', icon='code')), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='HTML that will be rendered on the page. Use as a temporary solution or last resort for something fancy that has not been enabled in a proper Wagtail block yet.', icon='placeholder', label='Raw HTML'))], blank=True)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
